apiVersion: v2
name: cray-node-problem-detector
version: 1.8.0
description: Cray node problem detecor for monitoring extra attributes on nodes
keywords:
  - node-problem-detector
  - cray-node-problem-detector
  - node
  - problem
  - detector
  - monitoring
home: "https://github.com/Cray-HPE/cray-node-problem-detector"
dependencies:
  - name: node-problem-detector
    version: 1.7.6
    repository: https://charts.helm.sh/stable
maintainers:
  - name: brantk-hpe
  - name: bo-quan
appVersion: 0.8.1
annotations:
  artifacthub.io/changes: |
    - kind: security
      description: Refactor to use patched CSM images
      links:
        - name: Github Issue
          url: https://github.com/Cray-HPE/cray-node-problem-detector/issues/4
        - name: Github PR
          url: https://github.com/Cray-HPE/cray-node-problem-detector/pull/3
  artifacthub.io/images: |
    - name: node-problem-detector
      image: artifactory.algol60.net/csm-docker/stable/k8s.gcr.io/node-problem-detector:v0.8.1
  artifacthub.io/license: MIT
