
#
# MIT License
#
# (C) Copyright 2021-2022 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
apiVersion: v2
name: cray-node-problem-detector
version: 1.9.0
description: Cray node problem detecor for monitoring extra attributes on nodes
keywords:
  - node-problem-detector
  - cray-node-problem-detector
  - node
  - problem
  - detector
  - monitoring
home: "https://github.com/Cray-HPE/cray-node-problem-detector"
dependencies:
  - name: node-problem-detector
    version: 1.7.6
    repository: https://charts.helm.sh/stable
maintainers:
  - name: bo-quan
appVersion: 0.8.10
annotations:
  artifacthub.io/changes: |
    - kind: security
      description: Refactor to use patched CSM images
      links:
        - name: Github Issue
          url: https://github.com/Cray-HPE/cray-node-problem-detector/issues/4
        - name: Github PR
          url: https://github.com/Cray-HPE/cray-node-problem-detector/pull/3
  artifacthub.io/images: |
    - name: node-problem-detector
      image: artifactory.algol60.net/csm-docker/stable/k8s.gcr.io/node-problem-detector:v0.8.10
  artifacthub.io/license: MIT
