#
# MIT License
#
# (C) Copyright 2021-2025 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# Default values for cray-node-problem-detector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

node-problem-detector:
  # These need to be set because kubernetes creates
  # role bindings by default specifically for npd
  nameOverride: node-problem-detector
  fullnameOverride: node-problem-detector
  serviceAccount:
    name: node-problem-detector

  image:
    repository: artifactory.algol60.net/csm-docker/stable/k8s.gcr.io/node-problem-detector
    tag: v0.8.20

  rbac:
    create: true
    pspEnabled: true

  settings:
    log_monitors:
      - /config/kernel-monitor.json

  resources:
    requests:
      memory: "64Mi"
      cpu: "125m"
    limits:
      memory: "256Mi"
      cpu: "3"

  securityContext:
    privileged: false

  # Monitor master nodes as well
  tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
